[package]
name = "aoc2020"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utility = { path = "../utility" }
color-eyre = "0.6.2"
bytecount = "0.6.3"
itertools = "0.10.5"
memchr = "2.5.0"
